export const SET_PLAYER_CURRENT_TRACK = 'SET_PLAYER_CURRENT_TRACK';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';

export const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';
