export const FETCH_PODCAST_START = 'FETCH_PODCAST_START';
export const FETCH_PODCAST_SUCCESS = 'FETCH_PODCAST_SUCCESS';
export const FETCH_PODCAST_FAIL = 'FETCH_PODCAST_FAIL';

export const SEARCH_PODCAST_START = 'SEARCH_PODCAST_START';
export const SEARCH_PODCAST_SUCCESS = 'SEARCH_PODCAST_SUCCESS';
export const SEARCH_PODCAST_FAIL = 'SEARCH_PODCAST_FAIL';

export const SET_CURRENT_PODCAST = 'SET_CURRENT_PODCAST';
